# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WVaXV1HQ73d2A6tPN8Mu-oSnen2610-F
"""

#Operators
def sum(a,b):
  print("The sum is",a+b)

def dif(a,b):
  print("The difference is",a-b)

def prod(a,b):
  print("The product is",a*b)

def quo(a,b):
  print("The quotient is",a/b)

#User Input
a=float(input("Enter the first number: "))
b=float(input("Enter the second number: "))
op=input("Enter the operator: ")

#Conditional Call
if(op=="+"):
  sum(a,b)

elif(op=="-"):
  dif(a,b)

elif(op=="*"):
  prod(a,b)

elif(op=="/"):
  quo(a,b)

else:
  print("Invalid Operator")